name: Deploiement continu Back-Office

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Production - Transfert FTP Back-Office
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du code source
        uses: actions/checkout@v4

      - name: Synchronisation FTP Hostinger Back
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVEUR }}
          username: ${{ secrets.FTP_UTILISATEUR }}
          password: ${{ secrets.FTP_MOT_DE_PASSE }}
          local-dir: ./api/
          server-dir: /public_html/api/